"""
src/research/jump_detection.py — Track B Phase 2
Jump score and EM soft separation for belief dynamics.

Model
-----
The logit return r_t is modelled as a mixture:

    r_t ~ (1-π) · N(0, σ_d²)  +  π · Laplace(0, b_j)

    diffusion component : N(0, σ_d²)       continuous Wiener noise
    jump component      : Laplace(0, b_j)  heavier-tailed jump arrivals

π      = prior jump probability (mixing weight, 0 < π < 1)
σ_d    = diffusion volatility (logit units per step)
b_j    = Laplace scale ≈ σ_j / sqrt(2)  (σ_j = typical jump size)

Why Laplace for jumps?
    Heavy-tailed relative to Normal; closed-form; analytically tractable.
    Equivalent to a double-exponential model common in jump-diffusion literature.

Soft EM assignment (E-step):
    p_jump(r) = P(jump | r)
              = π · f_jump(r) / [π · f_jump(r) + (1-π) · f_diff(r)]

Jump score (scalar summary):
    jump_score(r) = p_jump(r) ∈ [0, 1]
    > 0.5 → more likely a jump than diffusion
    > 0.9 → strong jump signal

No imports from Track A. Research only.
"""
from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Optional, Tuple

from .theory import EWMABeliefVol, EWMA_LAMBDA_DEFAULT


# ---------------------------------------------------------------------------
# Default hyperparameters
# ---------------------------------------------------------------------------

JUMP_PRIOR_PI:     float = 0.05   # 5% prior probability of jump on any step
JUMP_LAPLACE_B:    float = 0.30   # Laplace scale (≈ typical jump σ / √2 ≈ 0.42 logit)
DIFF_SIGMA_INIT:   float = 0.10   # initial diffusion σ estimate (logit units)
JUMP_SCORE_THRESH: float = 0.50   # threshold for hard classification


# ---------------------------------------------------------------------------
# Component densities
# ---------------------------------------------------------------------------

def _normal_pdf(x: float, sigma: float) -> float:
    """N(0, sigma²) density."""
    if sigma < 1e-10:
        return 0.0
    return math.exp(-0.5 * (x / sigma) ** 2) / (sigma * math.sqrt(2.0 * math.pi))


def _laplace_pdf(x: float, b: float) -> float:
    """Laplace(0, b) density: (1/2b) · exp(-|x|/b)."""
    if b < 1e-10:
        return 0.0
    return math.exp(-abs(x) / b) / (2.0 * b)


# ---------------------------------------------------------------------------
# Jump score
# ---------------------------------------------------------------------------

def jump_score(
    r: float,
    sigma_d: float = DIFF_SIGMA_INIT,
    b_j:     float = JUMP_LAPLACE_B,
    pi:      float = JUMP_PRIOR_PI,
) -> float:
    """
    Posterior probability that logit return r was generated by a jump.

    P(jump | r) = π · f_jump(r) / [π · f_jump(r) + (1-π) · f_diff(r)]

    Returns a value in [0, 1].
    Returns pi (prior) when densities are both zero (degenerate input).
    """
    f_jump = _laplace_pdf(r, b_j)
    f_diff = _normal_pdf(r, sigma_d)

    num = pi * f_jump
    den = num + (1.0 - pi) * f_diff

    if den < 1e-300:
        return pi   # degenerate: return prior

    return num / den


def is_jump(
    r: float,
    sigma_d: float = DIFF_SIGMA_INIT,
    b_j:     float = JUMP_LAPLACE_B,
    pi:      float = JUMP_PRIOR_PI,
    threshold: float = JUMP_SCORE_THRESH,
) -> bool:
    """Hard binary classification: True if jump_score(r) >= threshold."""
    return jump_score(r, sigma_d=sigma_d, b_j=b_j, pi=pi) >= threshold


# ---------------------------------------------------------------------------
# EM soft separator
# ---------------------------------------------------------------------------

@dataclass
class EMState:
    """
    Current parameter estimates for the EM jump/diffusion separator.

    pi      : mixing weight (jump probability)
    sigma_d : diffusion component std dev (logit units)
    b_j     : Laplace scale for jump component
    n_obs   : number of observations processed
    """
    pi:      float = JUMP_PRIOR_PI
    sigma_d: float = DIFF_SIGMA_INIT
    b_j:     float = JUMP_LAPLACE_B
    n_obs:   int   = 0

    def to_dict(self) -> dict:
        return {
            "pi":      self.pi,
            "sigma_d": self.sigma_d,
            "b_j":     self.b_j,
            "n_obs":   self.n_obs,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "EMState":
        return cls(
            pi=d["pi"],
            sigma_d=d["sigma_d"],
            b_j=d["b_j"],
            n_obs=d.get("n_obs", 0),
        )


@dataclass
class JumpDetectionResult:
    """Per-observation output from EMSeparator.step()."""
    r:          float   # logit return
    jump_score: float   # P(jump | r) ∈ [0,1]
    is_jump:    bool    # hard classification
    sigma_d:    float   # current diffusion σ estimate
    b_j:        float   # current Laplace scale
    pi:         float   # current jump prior
    n_obs:      int


class EMSeparator:
    """
    Online EM-style jump/diffusion separator.

    Maintains running estimates of (π, σ_d, b_j) using soft assignments.

    The M-step uses exponentially weighted updates rather than full batch EM,
    making it suitable for streaming data.

    Parameters
    ----------
    lambda_ewma : decay for EWMA-style parameter updates (default 0.94)
    pi_init     : initial jump prior
    sigma_d_init: initial diffusion σ
    b_j_init    : initial Laplace scale
    threshold   : jump_score threshold for hard classification
    """

    def __init__(
        self,
        lambda_ewma:  float = EWMA_LAMBDA_DEFAULT,
        pi_init:      float = JUMP_PRIOR_PI,
        sigma_d_init: float = DIFF_SIGMA_INIT,
        b_j_init:     float = JUMP_LAPLACE_B,
        threshold:    float = JUMP_SCORE_THRESH,
    ) -> None:
        self._state    = EMState(pi=pi_init, sigma_d=sigma_d_init, b_j=b_j_init)
        self._lambda   = lambda_ewma
        self._threshold = threshold

        # EWMA accumulators for M-step
        self._ewma_pi:     float = pi_init
        self._ewma_sigma2: float = sigma_d_init ** 2   # variance of diffusion
        self._ewma_b:      float = b_j_init

    # ------------------------------------------------------------------
    # Public interface
    # ------------------------------------------------------------------

    @property
    def state(self) -> EMState:
        return self._state

    def step(self, r: float) -> JumpDetectionResult:
        """
        Process one logit return r.

        E-step : compute soft assignment p_jump(r) with current parameters.
        M-step : update parameters using EWMA-weighted M-step equations.

        M-step updates (EWMA weighted):
            π        ← λ · π     + (1-λ) · p_j
            σ_d²     ← λ · σ_d² + (1-λ) · (1-p_j) · r² / (1-π)
            b_j      ← λ · b_j  + (1-λ) · p_j · |r| / π

        Clipping prevents degenerate parameter collapse.
        """
        s = self._state
        lam = self._lambda

        # E-step
        p_j = jump_score(r, sigma_d=s.sigma_d, b_j=s.b_j, pi=s.pi)

        # M-step (EWMA weighted)
        new_pi = lam * self._ewma_pi + (1.0 - lam) * p_j
        new_pi = max(1e-3, min(0.5, new_pi))  # keep pi in sensible range

        pi_safe = max(new_pi, 1e-4)
        one_minus_pi = max(1.0 - pi_safe, 1e-4)

        new_sigma2 = lam * self._ewma_sigma2 + (1.0 - lam) * (1.0 - p_j) * r * r / one_minus_pi
        new_sigma2 = max(1e-6, new_sigma2)

        new_b = lam * self._ewma_b + (1.0 - lam) * p_j * abs(r) / pi_safe
        new_b = max(1e-4, new_b)

        # Write back
        self._ewma_pi     = new_pi
        self._ewma_sigma2 = new_sigma2
        self._ewma_b      = new_b

        s.pi      = new_pi
        s.sigma_d = math.sqrt(new_sigma2)
        s.b_j     = new_b
        s.n_obs  += 1

        return JumpDetectionResult(
            r=r,
            jump_score=p_j,
            is_jump=p_j >= self._threshold,
            sigma_d=s.sigma_d,
            b_j=s.b_j,
            pi=s.pi,
            n_obs=s.n_obs,
        )

    def reset(self) -> None:
        self._state    = EMState(
            pi=JUMP_PRIOR_PI,
            sigma_d=DIFF_SIGMA_INIT,
            b_j=JUMP_LAPLACE_B,
        )
        self._ewma_pi     = JUMP_PRIOR_PI
        self._ewma_sigma2 = DIFF_SIGMA_INIT ** 2
        self._ewma_b      = JUMP_LAPLACE_B

    def to_dict(self) -> dict:
        return {
            "state":       self._state.to_dict(),
            "lambda":      self._lambda,
            "threshold":   self._threshold,
            "ewma_pi":     self._ewma_pi,
            "ewma_sigma2": self._ewma_sigma2,
            "ewma_b":      self._ewma_b,
        }

    @classmethod
    def from_dict(cls, d: dict) -> "EMSeparator":
        obj = cls(
            lambda_ewma=d.get("lambda", EWMA_LAMBDA_DEFAULT),
            threshold=d.get("threshold", JUMP_SCORE_THRESH),
        )
        obj._state        = EMState.from_dict(d["state"])
        obj._ewma_pi      = d.get("ewma_pi",     obj._state.pi)
        obj._ewma_sigma2  = d.get("ewma_sigma2", obj._state.sigma_d ** 2)
        obj._ewma_b       = d.get("ewma_b",      obj._state.b_j)
        return obj


# ---------------------------------------------------------------------------
# Batch utility
# ---------------------------------------------------------------------------

def detect_jumps_in_series(
    returns: list[float],
    sigma_d: float = DIFF_SIGMA_INIT,
    b_j:    float = JUMP_LAPLACE_B,
    pi:     float = JUMP_PRIOR_PI,
    threshold: float = JUMP_SCORE_THRESH,
) -> list[JumpDetectionResult]:
    """
    Apply fixed-parameter jump detection to a full returns series.
    Does not update parameters — purely a classification pass.
    Useful for offline analysis / backtesting.
    """
    return [
        JumpDetectionResult(
            r=r,
            jump_score=jump_score(r, sigma_d=sigma_d, b_j=b_j, pi=pi),
            is_jump=is_jump(r, sigma_d=sigma_d, b_j=b_j, pi=pi, threshold=threshold),
            sigma_d=sigma_d,
            b_j=b_j,
            pi=pi,
            n_obs=i + 1,
        )
        for i, r in enumerate(returns)
    ]
